version: '3.8'

services:
  # react-frontend:
  #   build:
  #     context: voluntario-frontend
  #     dockerfile: Dockerfile
  #   container_name: react-frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./voluntario-frontend/node_modules:/app/node_modules
  #     - .:/app
  #   # depends_on:
  #   #   - api
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
  
  # api:
  #   build:
  #     context: voluntario-backend
  #     dockerfile: Dockerfile
  #   container_name: api
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - redis-stack
  #   environment:
  #     - SPRING_DATASOURCE_URL=postgresql://postgres:postgres@db:5432/voluntarioDB
  #     - REDIS_URL=redis://session_redis:6379
  #     - REDIS_PASSWORD=session
  #     - PORT=8080
  #   networks:
  #     - redisnet
  
  db:
    image: postgres:12
    container_name: database_postgres
    environment:
      POSTGRES_DB: voluntarioDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - redis-stack-data:/bitnami/redis/data
    container_name: session_redis
    networks:
      - redisnet
    ports:
      - "8001:8001"
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: session
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      interval: 30s
      timeout: 15s
      retries: 10

volumes:
  redis-stack-data:
    driver: local

  pgdata:
    driver: local

  # session_store:
  #   driver: local

networks:
  redisnet: { }