version: '3.8'

services:
  db:
    image: postgres:12
    container_name: database
    environment:
      POSTGRES_DB: voluntarioDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
